### ISSUE TITLE
Configuração Styled component + Babel

### ISSUE THREAD

**Issue by Claytonrss** [milealmeida/side-project-pokemon#2]
Aparentemente no NextJS13 podemos substituir aquele plugin do babel styled-component(.babelrc) 
por uma configuração direta do compiler (.next.config.js)

https://nextjs.org/docs/advanced-features/compiler#styled-components

compiler: {
    styledComponents: true
}

Acho que vale a pena testar;

**Comment by milealmeida** [comment]
Ajustei
